(i18nsupport) Fix linux/clang compile error (#19628)
* (i18nsupport) Fix linux/clang compile error

This fixes a simple compile error on linux/clang.

```
 In file included from ... O3DEQtControlGallery.dir/Unity/unity_3_cxx.cxx:19:
 ... StyleSheetPage.cpp:84:21: error: loop variable 'fruit' creates a copy from type 'QString const' [-Werror,-Wrange-loop-construct]
     for (const auto fruit : fruitList)
                     ^
 ... StyleSheetPage.cpp:84:10: note: use reference type 'QString const &' to prevent copying
     for (const auto fruit : fruitList)
          ^~~~~~~~~~~~~~~~~~
                     &
 1 error generated.
```

Signed-off-by: Nicholas Lawson <70027408+nick-l-o3de@users.noreply.github.com>

* Fixes a false memory leak causing tests to fail

I call this a "False" memory leak because the situation
is that it is lazy allocating a vector of strings, when first used
and not technically cleaning them up before program exit.

However, they are stored in a global static, which will in fact
be cleared during `atexit` cleanup, so it isn't a true leak.

However, our in built memory leak detection stuff picks it up
because it strictly requires memory created during the program
execution to be cleaned up before program exit.

Signed-off-by: Nicholas Lawson <70027408+nick-l-o3de@users.noreply.github.com>

---------

Signed-off-by: Reece Hagan <drogonmar@tuyuji.com>
Signed-off-by: Nicholas Lawson <70027408+nick-l-o3de@users.noreply.github.com>
Signed-off-by: guillaume-haerinck <guillaume.haerinck@outlook.com>
Co-authored-by: Reece Hagan <drogonmar@tuyuji.com>
Co-authored-by: Guillaume Haerinck <guillaume.haerinck@outlook.com>